# Generated by Django 3.0.7 on 2020-06-18 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('snippet', models.CharField(max_length=200)),
                ('vector_length', models.FloatField(default=0)),
                ('max_freq', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('df', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freq', models.IntegerField(default=0)),
                ('tf_idf', models.FloatField(default=0.0)),
                ('locations', models.CharField(max_length=5000)),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Document')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Word')),
            ],
        ),
    ]
