# Generated by Django 3.0.7 on 2020-06-29 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword', to='documents.Word')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='root_word', to='documents.Word')),
            ],
        ),
        migrations.CreateModel(
            name='correlatedDocs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corrDoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrDoc', to='documents.Document')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc', to='documents.Document')),
            ],
        ),
    ]
