# Generated by Django 3.0.7 on 2020-06-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_correlateddocs_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='correlateddocs',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
